using System;
using Microsoft.Xna.Framework;

namespace XNAMachinationisRatio.Physics {
    /// <summary>
    /// A contact generated by a collision
    /// </summary>
    class Contact {
        private long mTime;
        private float mDepth;
        private Vector3 mNormal; 

        /// <summary>
        /// Ctor
        /// </summary>
        /// <param name="pTime">Contact Time</param>
        /// <param name="pDepth">Depth</param>
        /// <param name="pNormal">Normal</param>
        public Contact(long pTime, float pDepth, Vector3 pNormal) {
            mTime = pTime;
            mDepth = pDepth;
            mNormal = pNormal;
        }

        public long Time{
            get { return mTime; }
        }
        public float PenetrationDepth {
            get { return mDepth; }
        }

        public Vector3 Penetration {
            get { return Vector3.Multiply(mNormal,mDepth); }
        }
    }
}
